# Generated by Django 5.0.1 on 2024-02-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('owned_crops', models.ManyToManyField(related_name='ownership', to='backend.crop')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='owner',
            field=models.ManyToManyField(related_name='ownership', to='backend.user'),
        ),
    ]
